### ISSUE TITLE
Plugin can't be installed when using only API

### ISSUE THREAD

**Issue by htuscher** [FriendsOfShopware/FroshTemplateMailMjml#1]
As the plugin installation checks only for the local compiler to be installed:
```php
        if (MjmlCompiler::isMjmlInstalled() === null) {
            throw new \RuntimeException('MJML must be installed and accessable using $PATH');
        }
```

It's impossible to install the plugin, when you have only the MJML API configured.

**Comment by shyim** [comment]
Yea. You are right 😄 . Thanks

**Comment by larsbo** [comment]
![why](https://i.imgflip.com/2pjoyd.jpg)
