### ISSUE TITLE
Content is not set in WebMjmlCompiler

### ISSUE THREAD

**Issue by htuscher** [FriendsOfShopware/FroshTemplateMailMjml#2]
https://github.com/FriendsOfShopware/FroshTemplateMailMjml/blob/79a9fa6ae3adcd2ccb22a54ce2c487ed1fbb68a0/Components/WebMjmlCompiler.php#L62

I think:
```php
$content = $response['html'];
```

is missing here

**Comment by shyim** [comment]
🙈
