### ISSUE TITLE
Including files is not possible with WebCompiler

### ISSUE THREAD

**Issue by htuscher** [FriendsOfShopware/FroshTemplateMailMjml#3]
You can't use one of
```
      {include file="header.html.mjml"}
      <mj-include path="./header.html.mjml" />
```

Because the template is just loaded via `file_get_contents` and send to the API.

**Comment by shyim** [comment]
MJML seems to dont support mj-include-path on api. See https://mjml.io/api/documentation/

**Comment by htuscher** [comment]
Yes, but an idea would e.g. be to write a `mj-include-path` resolver which does just string-replace with file_get_contents on those files?

**Comment by shyim** [comment]
Does the mj-include-path just appending the content? 🤔

**Comment by htuscher** [comment]
Looks like it:
https://github.com/mjmlio/mjml/blob/50b08513b7a651c234829abfde254f106a62c859/packages/mjml-cli/src/helpers/fileContext.js
https://github.com/mjmlio/mjml/blob/c7195156e0cb0db5b429af6044df7dc7f1aa847e/packages/mjml-parser-xml/src/index.js
